# APIs explorer (for more): https://developers.google.com/apis-explorer/
# Old 
SOME_APIS = [
    ('androidmanagement', 'v1'),
    ('books', 'v1'),
    ('blogger', 'v3'),
    ('calendar', 'v3'),
    ('cloudsearch', 'v1'),
    ('compute', 'v1'),
    ('container', 'v1'),
    ('discovery', 'v1'),
    ('drive', 'v3'),
    ('fitness', 'v1'),
    ('gmail', 'v1'),
    ('indexing', 'v3'),
    ('kgsearch', 'v1'),
    ('oauth2', 'v2'),
    ('people', 'v1'),
    ('plus', 'v1'),
    ('safebrowsing', 'v4'),
    ('sheets', 'v4'),
    ('storagetransfer', 'v1'),
    ('streetviewpublish', 'v1'),
    ('surveys', 'v2'),
    ('tasks', 'v1'),
    ('urlshortener', 'v1'),
    ('webfonts', 'v1'),
    ('websecurityscanner', 'v1alpha'),
    ('youtube', 'v3'),
    ('youtubeAnalytics', 'v2'),
    ('youtubereporting', 'v1'),
]